import transformers
import torch
from transformers import Trainer
from transformers.trainer_pt_utils import LabelSmoother
import wandb
import random
from torch.utils.data import DataLoader
from torch.cuda.amp import autocast

IGNORE_TOKEN_ID = LabelSmoother.ignore_index

class CllmTrainer(Trainer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        args = kwargs["args"]
        self.train_step_cnt = 0
        self.max_new_tokens = args.max_new_tokens
        self.use_gt_labels = args.use_gt_labels

    def training_step(self, model, inputs, num_items_in_batch):
        self.train_step_cnt += 1
        return self.consistency_training_step(model, inputs)

    def consistency_training_step(self, model, inputs):

        max_new_tokens = self.max_new_tokens      

        jacobian_trajectory = inputs["jacobian_trajectory"]
        input_masks = inputs["attention_mask"]
        bsz = jacobian_trajectory[0].shape[0]
        eos_reached = torch.tensor([False] * bsz).to(model.device)

        ### tokens generated after <eos> are set to <pad>
        for i in range(len(jacobian_trajectory)):
            for j in range(bsz):
                trajectory_len = torch.sum(input_masks, dim=-1)
                # find the first accurate <EOS>
                eos_positions = torch.where(jacobian_trajectory[i][j, :(trajectory_len[j]-max_new_tokens)]==self.processing_class.eos_token_id)[0]
                if len(eos_positions)==0:
                    continue
                # otherwise, set tokens coming after the accurate <EOS> as pad 
                eos_reached[j] = True
                trajectory_copy = jacobian_trajectory[i].clone().detach()
                eos_pos = eos_positions[0]
                trajectory_copy[j, int(eos_pos)+1:] = self.processing_class.pad_token_id
                jacobian_trajectory[i] = trajectory_copy  

        ### compute AutoRegression loss ###
        # use labels to avoid pattern collapse
        if self.use_gt_labels:
            labels = inputs['labels_ids']
        else:
            labels = inputs['teacher_output_ids']
        # TODO: check if it's right when batch size > 1
        labels = torch.tensor(labels).to(model.device)
        attention_mask = torch.full_like(labels, 1).to(model.device)
        # FlashAttention only support fp16 and bf16 data type
        with autocast(dtype=torch.bfloat16):
            label_student_model_output = model(labels, attention_mask)

        label_smoother = LabelSmoother(epsilon=0.1, ignore_index= -100)
        loss_ar = label_smoother(label_student_model_output, labels, shift_labels=True)
        loss_ar *= 10
        if self.args.qlora:
            loss_ar.requires_grad = True
        print(f'loss ar: {loss_ar} computed! performing backward pass...')
        with self.accelerator.accumulate(model):
            self.accelerator.backward(loss_ar)

        # ========================================== #
        ### compute soft Consistency loss (global) ###
        # Get teacher logits from converged point
        attention_mask_last = torch.full_like(jacobian_trajectory[0], 1).to(model.device)
        attention_mask_last = jacobian_trajectory[-1] != self.processing_class.pad_token_id
        logits_last =  self.get_logits(model, jacobian_trajectory[-1].clone().detach(), attention_mask_last)
        
        # random select one point from trajectory
        i = random.choice(range(len(jacobian_trajectory))[:-1])
        attention_mask = torch.full_like(jacobian_trajectory[0], 1).to(jacobian_trajectory[0].device)
        attention_mask = jacobian_trajectory[i] != self.processing_class.pad_token_id
        logits_i = self.get_logits(model, jacobian_trajectory[i].clone().detach(), attention_mask)

        output_mask = jacobian_trajectory[i][..., 1:] == self.processing_class.pad_token_id
        # We do not calculate the cross entrophy of same logits to minimize misleading gradients
        for j in range(bsz):
            end_of_mask_position = torch.where(jacobian_trajectory[i][j, 1:] != jacobian_trajectory[-1][j, 1:])[0]
            if len(end_of_mask_position)==0:
                output_mask[j, :] = True
            else:
                output_mask[j, :end_of_mask_position[0]] = True
        
        loss_global = self.soft_cross_entropy(
                    logits_i[..., :-1, :].float(), # logits generated by the last token is dropped
                    logits_last[..., :-1, :].to(logits_i.device).clone().detach().float(),
                    output_mask.to(logits_i.device)
        )
        if self.args.qlora:
            loss_global.requires_grad = True
        print(f'loss global {loss_global} computed! performing backward pass...')
        with self.accelerator.accumulate(model):
            self.accelerator.backward(loss_global)

        # ========================================== #
        ### compute hard Consistency loss (global) ###
        # random select one point from trajectory
        #i = random.choice(range(len(jacobian_trajectory))[:-1])

        #attention_mask = torch.full_like(jacobian_trajectory[0], 1).to(jacobian_trajectory[0].device)
        #attention_mask = jacobian_trajectory[i] != self.processing_class.pad_token_id
        #with autocast(dtype=torch.bfloat16):
        #    trajectiory_i_student_model_output = model(jacobian_trajectory[i].clone().detach(), attention_mask)

        #output_mask = jacobian_trajectory[i][..., 1:] == self.processing_class.pad_token_id
        # We do not calculate the cross entrophy of same logits to alleviate misleading gradients
        #for j in range(bsz):
        #    end_of_mask_position = torch.where(jacobian_trajectory[i][j, 1:] != jacobian_trajectory[-1][j, 1:])[0]
        #    if len(end_of_mask_position)==0:
        #        jacobian_trajectory[-1][j, 1:] = IGNORE_TOKEN_ID
        #    else:
        #        jacobian_trajectory[-1][j, :end_of_mask_position[0]] = IGNORE_TOKEN_ID
        #loss_global = label_smoother(trajectiory_i_student_model_output, jacobian_trajectory[-1].clone().detach(), shift_labels=True)
        #if self.args.qlora:
        #    loss_global.requires_grad = True
        #print(f'loss global {loss_global} computed! performing backward pass...')
        
        #with self.accelerator.accumulate(model):
        #    self.accelerator.backward(loss_global)

        ### Logging results on wandb and syncing processes ###
        if self.args.local_rank == 0:
            wandb.log({"ar loss": loss_ar})
            wandb.log({"consistency loss": loss_global})

        # sync processes
        torch.distributed.barrier()
        loss = loss_ar.detach() + loss_global.detach()

        return loss

    def log(self, logs, *args, **kwargs):

        if 'loss' in logs and logs['loss'] == -1:
            del logs['loss']
    
        super().log(logs)


    def get_train_dataloader(self):
        # Create custom DataLoader with shuffle set to False
        shuffle = True
        dataloader_params = {
            "batch_size": self.args.per_device_train_batch_size,
            "shuffle": shuffle,
            "num_workers": self.args.dataloader_num_workers,
            "pin_memory": self.args.dataloader_pin_memory,
        }

        return self.accelerator.prepare(DataLoader(self.train_dataset, **dataloader_params))

    ###################### Helper Functions #############################
    def soft_cross_entropy(self, predicts, targets, padding_mask):
        # TODO: support batch_size >1 here.
        if (~padding_mask).sum() == 0:
            return 0*predicts[0][0][0]
        predict_log_prob = torch.nn.functional.log_softmax(predicts, dim=-1)
        targets_prob = torch.nn.functional.softmax(targets, dim=-1)
        entropy = -targets_prob * predict_log_prob
        expand_mask = padding_mask.unsqueeze(-1).expand_as(entropy)
        entropy.masked_fill_(expand_mask, 0)
        mean_entropy = entropy.sum() / (~padding_mask).sum()
        return mean_entropy

    def get_logits(self, model, input_ids, attention_mask):

        # FlashAttention only support fp16 and bf16 data type
        with autocast(dtype=torch.bfloat16):
            logits = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
        ).logits
            
        return logits

